// ============================================================================
// 评测题库（演示用）
// ----------------------------------------------------------------------------
// 仅录入题目与标准答案；系统回答、得分、是否正确拒答等结果字段，
// 由 /api/evaluation 触发"运行评测"时调用真实问答链路后回填，
// 不预设任何漂亮指标。
// ============================================================================

import type { EvaluationItem } from "@/lib/types";
import { NUMERIC_GOLDEN_QUESTIONS } from "../rag/eval/goldenQuestions.ts";

const NUMERIC_EVALUATION: EvaluationItem[] = NUMERIC_GOLDEN_QUESTIONS.map(
  (question, index) => ({
    id: `eval-numeric-${String(index + 1).padStart(3, "0")}`,
    seq: `N${String(index + 1).padStart(3, "0")}`,
    scenario: "PDF数值回归",
    question: question.query,
    standardAnswer: question.expectedAnswerValues.join("；"),
    correctFile: question.sourceHint,
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedAnswerValues: question.expectedAnswerValues,
    forbiddenAnswerValues: question.forbiddenAnswerValues,
    expectedBehavior: "必须输出正确数值，且不得出现 PDF 解析乱序值。",
  })
);

export const MOCK_EVALUATION: EvaluationItem[] = [
  {
    id: "eval-1",
    question: "二类居住用地是什么？",
    standardAnswer:
      "二类居住用地（R2）指市政公用设施齐全、布局完整、环境良好，以多、中、高层住宅为主的用地。",
    correctFile: "城市用地分类与规划建设用地标准（演示版）.pdf",
    correctArticle: "第三点二条",
    correctPage: "18",
    shouldRefuse: false,
  },
  {
    id: "eval-2",
    question: "商务金融用地的定义是什么？",
    standardAnswer:
      "商务金融用地（B2）指金融、保险、证券等综合性办公及商务活动用地，不包括经营性销售为主的商业用地。",
    correctFile: "城市用地分类与规划建设用地标准（演示版）.pdf",
    correctArticle: "第三点五条",
    correctPage: "24",
    shouldRefuse: false,
  },
  {
    id: "eval-3",
    question: "商业用地和商务金融用地有什么区别？",
    standardAnswer:
      "B1 商业用地以面向公众的经营性销售、餐饮、住宿等活动为主；B2 商务金融用地以办公及商务活动为主，不含经营性销售。",
    correctFile: "城市用地分类与规划建设用地标准（演示版）.pdf",
    correctArticle: "第三点四条",
    correctPage: "23",
    shouldRefuse: false,
  },
  {
    id: "eval-4",
    question: "居住用地的绿地率不应低于多少？",
    standardAnswer: "居住用地绿地率不应低于30%；旧区改建不应低于25%。",
    correctFile: "控制性详细规划技术规定（演示版）.docx",
    correctArticle: "第二十六条",
    correctPage: "42",
    shouldRefuse: false,
  },
  {
    id: "eval-5",
    question: "大于90平方米的住宅每户停车位最低配建标准是多少？",
    standardAnswer: "建筑面积大于90平方米的住宅，每户不应少于1.0个停车位。",
    correctFile: "建设项目停车配建标准（演示版）.pdf",
    correctArticle: "第八条",
    correctPage: "12",
    shouldRefuse: false,
  },
  {
    id: "eval-6",
    question: "商业建筑每100平方米建筑面积停车位配建标准是多少？",
    standardAnswer: "商业建筑每100平方米建筑面积不应少于0.8个停车位。",
    correctFile: "建设项目停车配建标准（演示版）.pdf",
    correctArticle: "第十二条",
    correctPage: "16",
    shouldRefuse: false,
  },
  {
    id: "eval-7",
    question: "二类居住用地的容积率上限是多少？",
    standardAnswer:
      "应拒答：技术规定未统一规定容积率上限，需以经批准的控规图则逐地块确定。",
    correctFile: "控制性详细规划技术规定（演示版）.docx",
    correctArticle: "第十八条",
    correctPage: "30",
    shouldRefuse: true,
  },
  {
    id: "eval-8",
    question: "某地块容积率3.0、限高80米、建筑密度40%的组合是否可行？",
    standardAnswer:
      "应拒答：属于指标组合可行性判断，超出本 MVP 法规条文查询范围。",
    correctFile: "—",
    correctArticle: "—",
    correctPage: "—",
    shouldRefuse: true,
  },
  {
    id: "eval-9",
    question: "工业用地的绿地率要求是多少？",
    standardAnswer:
      "应拒答：当前知识库未收录工业用地绿地率的明确条文。",
    correctFile: "—",
    correctArticle: "—",
    correctPage: "—",
    shouldRefuse: true,
  },
  {
    id: "eval-10",
    question: "请帮我判断这个项目能不能通过规划审批。",
    standardAnswer: "应拒答：属于审批结论判断，超出 MVP 范围。",
    correctFile: "—",
    correctArticle: "—",
    correctPage: "—",
    shouldRefuse: true,
  },
  {
    id: "eval-11",
    question: "办公建筑每100平方米停车位配建标准是多少？",
    standardAnswer: "办公建筑每100平方米建筑面积不应少于0.6个停车位。",
    correctFile: "建设项目停车配建标准（演示版）.pdf",
    correctArticle: "第十二条",
    correctPage: "16",
    shouldRefuse: false,
  },
  {
    id: "eval-12",
    question: "旧区改建居住用地绿地率最低是多少？",
    standardAnswer: "旧区改建居住用地绿地率不应低于25%。",
    correctFile: "控制性详细规划技术规定（演示版）.docx",
    correctArticle: "第二十六条",
    correctPage: "42",
    shouldRefuse: false,
  },
  ...NUMERIC_EVALUATION,
];

export const ENTERPRISE_EVALUATION: EvaluationItem[] = [
  {
    id: "enterprise-eval-001",
    seq: "E001",
    scenario: "项目权限",
    userId: "user-employee-riverfront",
    question: "片区控规优化项目的用地调整原则是什么？",
    standardAnswer: "已授权普通员工应能基于片区控规优化项目资料回答，并给出项目资料引用。",
    correctFile: "片区控规优化项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "张明已授权片区控规优化项目，应正常回答并展示引用。",
  },
  {
    id: "enterprise-eval-002",
    seq: "E002",
    scenario: "项目权限",
    userId: "user-employee-industrial",
    question: "片区控规优化项目的成果提交要求有哪些？",
    standardAnswer: "未授权普通员工应收到无权访问提示，不展示原文或 citation。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: true,
    expectedBehavior: "陈珊未授权片区控规优化项目，应返回无权提示且不泄露引用。",
  },
  {
    id: "enterprise-eval-003",
    seq: "E003",
    scenario: "项目负责人",
    userId: "user-manager-riverfront",
    question: "片区控规优化项目需要提交哪些图纸和说明文件？",
    standardAnswer: "项目负责人应可访问自己负责项目的成果资料并正常回答。",
    correctFile: "片区控规优化项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "李婷作为片区控规优化项目负责人，应可正常回答。",
  },
  {
    id: "enterprise-eval-004",
    seq: "E004",
    scenario: "项目负责人",
    userId: "user-manager-tod",
    question: "TOD 综合开发项目的交通接驳设计重点是什么？",
    standardAnswer: "项目负责人应可访问自己负责的 TOD 项目资料并回答交通接驳设计重点。",
    correctFile: "TOD 综合开发项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "周航作为 TOD 项目负责人，应正常回答。",
  },
  {
    id: "enterprise-eval-005",
    seq: "E005",
    scenario: "项目权限",
    userId: "user-employee-riverfront",
    question: "TOD 综合开发项目的地块开发强度控制要求是什么？",
    standardAnswer: "未授权用户命中 TOD 项目资料时，应提示存在相关资料但当前账号无权访问。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: true,
    expectedBehavior: "张明未授权 TOD 项目，应返回无权提示，citations 为空。",
  },
  {
    id: "enterprise-eval-006",
    seq: "E006",
    scenario: "管理员",
    userId: "user-admin",
    question: "TOD 综合开发项目和产业园城市设计项目分别有哪些成果要求？",
    standardAnswer: "管理员应能跨项目检索并比较两个项目的成果要求。",
    correctFile: "项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "王磊作为管理员，应可跨项目综合回答。",
  },
  {
    id: "enterprise-eval-007",
    seq: "E007",
    scenario: "开发人员",
    userId: "user-developer",
    question: "TOD 综合开发项目的核心技术指标有哪些？",
    standardAnswer: "开发人员权限等同管理员，应可访问全部项目资料并回答。",
    correctFile: "TOD 综合开发项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "赵工作为开发人员，应可访问全部项目资料。",
  },
  {
    id: "enterprise-eval-008",
    seq: "E008",
    scenario: "通用企业知识",
    userId: "user-employee-riverfront",
    question: "公司报销流程是什么？",
    standardAnswer: "公开企业知识应对普通员工可见，并按流程类知识回答。",
    correctFile: "企业制度或财务报销资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "普通员工应可访问公开财务/制度知识。",
  },
  {
    id: "enterprise-eval-009",
    seq: "E009",
    scenario: "IT 与行政",
    userId: "user-employee-riverfront",
    question: "新员工如何申请设计软件账号？",
    standardAnswer: "公开 IT/行政知识应正常回答申请入口、审批人和注意事项。",
    correctFile: "IT与行政知识",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "普通员工应可访问公开 IT 与行政知识。",
  },
  {
    id: "enterprise-eval-010",
    seq: "E010",
    scenario: "项目权限",
    userId: "user-employee-industrial",
    question: "建筑方案报审资料需要包含哪些附件？",
    standardAnswer: "根据该资料权限，已授权则回答，未授权则提示无权。",
    correctFile: "建筑方案报审资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "按建筑方案报审资料的项目授权决定是否回答。",
  },
  {
    id: "enterprise-eval-011",
    seq: "E011",
    scenario: "文档元数据",
    userId: "user-manager-riverfront",
    question: "请列出片区控规优化项目的负责人、所属部门和权限等级。",
    standardAnswer: "可回答项目资料负责人、部门、权限等级等文档元数据。",
    correctFile: "片区控规优化项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "项目负责人应能看到自己负责项目的文档元数据。",
  },
  {
    id: "enterprise-eval-012",
    seq: "E012",
    scenario: "管理员",
    userId: "user-admin",
    question: "当前知识库里有哪些项目资料分类？",
    standardAnswer: "管理员应能查看完整分类和项目资料概览。",
    correctFile: "知识库文档元数据",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "管理员可查看完整项目资料分类概览。",
  },
  {
    id: "enterprise-eval-013",
    seq: "E013",
    scenario: "开发工具保护",
    userId: "user-employee-riverfront",
    question: "检索调试页面在哪里？",
    standardAnswer: "普通用户不应看到开发工具入口；直接访问开发页也应提示仅开发人员可见。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: true,
    expectedBehavior: "普通员工不显示检索调试、评测、切分查看等开发工具入口。",
  },
  {
    id: "enterprise-eval-014",
    seq: "E014",
    scenario: "开发人员",
    userId: "user-developer",
    question: "我能查看切分查看、检索调试和评测页面吗？",
    standardAnswer: "开发人员应显示并可访问切分查看、检索调试和评测入口。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "开发人员可见开发工具入口。",
  },
  {
    id: "enterprise-eval-015",
    seq: "E015",
    scenario: "无权防泄露",
    userId: "user-employee-riverfront",
    question: "请引用 TOD 综合开发项目原文说明。",
    standardAnswer: "未授权时不得展示 TOD 项目原文，不返回 citation。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: true,
    expectedBehavior: "无权场景不能泄露原文或引用。",
  },
  {
    id: "enterprise-eval-016",
    seq: "E016",
    scenario: "管理员",
    userId: "user-admin",
    question: "请比较片区控规优化、产业园城市设计、TOD 综合开发三个项目的成果交付差异。",
    standardAnswer: "管理员应可跨项目综合比较三个项目的成果交付差异。",
    correctFile: "项目资料",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "管理员跨项目综合回答。",
  },
  {
    id: "enterprise-eval-017",
    seq: "E017",
    scenario: "行业垂直知识",
    userId: "user-employee-industrial",
    question: "规划法规中关于停车配建的要求是什么？",
    standardAnswer: "公开行业垂直知识应正常回答停车配建要求并引用法规或标准。",
    correctFile: "停车标准",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: false,
    expectedBehavior: "普通员工可访问公开行业知识。",
  },
  {
    id: "enterprise-eval-018",
    seq: "E018",
    scenario: "权限解释",
    userId: "user-manager-riverfront",
    question: "为什么我看不到 TOD 综合开发项目资料？",
    standardAnswer: "应解释当前账号只能访问公开资料、被授权项目或自己负责的项目资料。",
    correctFile: "",
    correctArticle: "",
    correctPage: "",
    shouldRefuse: true,
    expectedBehavior: "解释项目权限边界，不泄露 TOD 资料正文。",
  },
];

export function resolveEvaluationUserId(
  item: Pick<EvaluationItem, "userId">
): string | undefined {
  const userId = item.userId?.trim();
  return userId ? userId : undefined;
}
